### ISSUE TITLE
Code sample tabs flicker / render loop

### ISSUE THREAD

**Issue by benri** [anypoint-web-components/anypoint-tabs#12] opened 2021-04-27 20:55 UTC
On the latest version of this package, I am noticing a flicker of the tabs / render loop when used within api method documentation, under the "code samples" section.

Screen record of the flicker can be viewed here:
https://drive.google.com/file/d/1ZpDwby70UN76ZU6RhGFYhlMhvnVlZx0d/view?usp=sharing

version: 0.1.15
package: @anypoint-web-components/anypoint-tabs

To repro the issue:
1. create `anypoint-tabs` element with `scrollable=true`

Observations:
- I believe the issue is caused by the following code change:
```
      hideScrollButtons: { type: Boolean, reflect: true },
```

- I think when hideScrollButtons is updated to attribute, it triggers a render
- and then when it renders, it calculates a new value for hideScrollButtons - this is leading to an infinite render loop

**Comment by deiteris** [comment] 2021-05-26 16:48
Facing the same issue. @jarrodek, @TwoPlusTwoOne?

**Comment by TwoPlusTwoOne** [comment] 2021-06-04 17:31
I'll a look into this next week, pardon the delay. I was pretty sure I had fixed it in 0.1.17

@deiteris could you share the UI when you're able to reproduce it?

**Comment by deiteris** [comment] 2021-06-04 21:02
@TwoPlusTwoOne, what do you mean by the UI? I can share a bundle that reproduces the issue, if it helps. Here's the zip: [dist.zip](https://github.com/anypoint-web-components/anypoint-tabs/files/6601206/dist.zip)

On the screenshot you can see that I'm currently on version 0.1.17 of this package.
![image](https://user-images.githubusercontent.com/6103913/120862105-0f25d700-c591-11eb-906a-cc15a1b42d49.png)

**Comment by TwoPlusTwoOne** [comment] 2021-07-13 14:20
@deiteris this should be fixed now with #19 , could you confirm please?

**Comment by deiteris** [comment] 2021-07-13 16:57
Yes, looks like it's fixed with 0.1.19. Thanks!

**Closed** 2021-07-14 20:17 UTC
